import React, { createContext, useContext, useState } from 'react';

// Definir las traducciones
const translations = {
  es: {
    web_designer: 'Diseñador Web & UX/UI',
    skills: 'Habilidades',
    software: 'Software',
    about_me: ' Sobre Mí',
    experience: ' Experiencia',
    education: ' Educación',
    ai_tools: ' Herramientas de IA',
    projects: 'Proyectos',
    ux_ui_designs: 'Diseños UX/UI',
    welcome: 'Bienvenido',
    aiTools: 'Herramientas de IA',
    contact: 'Contacto',
    enterVR: 'Entrar en VR',
    exitVR: 'Salir de VR',
    generativeAI: 'IA Generativa',
    videoAnimation: 'Video y Animación',
    textChatbots: 'Chatbots de Texto',
    designTools: 'Herramientas de Diseño',
    socialMedia: 'Redes Sociales',
    search: 'Búsqueda',
    audioTools: 'Herramientas de Audio',
    codeTools: 'Herramientas de Código',
    research: 'Investigación',
    otherTools: 'Otras Herramientas',
    aiToolsTitle: 'Herramientas de IA',
    aboutMe: 'Sobre Mí',
    graphicDesign: 'Diseño gráfico',
    webDesign: 'Diseño web',
    uiUxDesign: 'Diseño UX/UI',
    webDevelopment: 'Desarrollo web',
    aboutMeDescription: 'Tengo experiencia dando soluciones de Diseño y Desarrollo Web a problemas de negocios reales, tratando con clientes y equipos, a nivel nacional e internacional, para clientes de Argentina, Estados Unidos, Uruguay y España. Me especialicé en Paid Media creando anuncios en Meta Ads y Google Ads. Uso mis habilidades en más de 50 herramientas de Inteligencia Artificial (AI), y las aplico en el desarrollo de mi trabajo, mejorando la calidad, velocidad y automatización de mi trabajo.',
    aboutMeMission: 'Amo lo que hago! Mi misión es ayudar a transformar la vida de muchas personas, negocios y empresas, creando soluciones y experiencias web únicas y de alta calidad.',
    projectsTitle: 'Proyectos',
    project1Title: 'Babz App',
    project1Description: 'Plataforma de mensajería con reacciones de video únicas. Diseño de Identidad y Desarrollo Web. Diseño de producto completo incluyendo sistema de identidad de marca, UI Kit y experiencia de usuario.',
    project1Tech: 'UI Kit,Brand Design,UX Design,Firebase,Analytics',
    project2Title: 'SNS Web Services',
    project2Description: 'Plataforma integral de servicios web para más de 50 clientes, incluyendo hosting SSD, diseño UX/UI, desarrollo web y marketing digital.',
    project2Tech: 'UX/UI Design,Web Development,Hosting,Digital Marketing',
    project3Title: 'Neorelax',
    project3Description: 'Tienda online de productos de relajación y bienestar.',
    project3Tech: 'WordPress,WooCommerce,CSS,Payment Gateway',
    project4Title: 'Soluciones Gastronómicas',
    project4Description: 'E-commerce para venta de productos gastronómicos.',
    project4Tech: 'WordPress,WooCommerce,JavaScript,UI/UX Design',
    project5Title: 'El Jardín de la Plaza',
    project5Description: 'Diseño y desarrollo de sitio web para escuela de jardín de infantes.',
    project5Tech: 'WordPress,Elementor,CSS,Responsive Design',
    project6Title: 'Clazzical Interactive 3D Website',
    project6Description: 'Desarrollo de sitio web con remera 3D interactiva.',
    project6Tech: 'Web Development,UX/UI Design,Web Design,React,Git',
    name: 'Tobias Etchelet',
    subtitle: 'Desarrollador Web Full Stack y Diseñador UX/UI',
    skillsTitle: 'Habilidades',
    experienceTitle: 'Experiencia',
    experienceLaboral: 'Experiencia Laboral',
    contactTitle: 'Contacto',
    webDeveloper: 'Desarrollador Web',
    webDevSkills: 'HTML,CSS,JavaScript,Bootstrap 5',
    graphicDesignSkills: 'Teoría del Diseño,Teoría del Color,Tipografías,Producción Gráfica',
    webDesignSkills: 'Diseño de Interfaz,Diseño Responsivo,Gestión de Contenidos,WebMaster',
    uxUiDesign: 'Diseño UX/UI',
    uxUiDesign1: 'Diseño UI: Enfocado en la parte visual, todo lo visible para el usuario.',
    uxUiDesign2: 'Diseño UX: Orientado a la experiencia del usuario en la web o aplicación.',
    metaAds: 'Meta Ads',
    metaAdsSkill1: 'Más de 60 campañas realizadas para 20 empresas de diferentes nichos.',
    metaAdsSkill2: 'Auditoría interna y externa.',
    metaAdsSkill3: 'Establecimiento de objetivos para la campaña.',
    metaAdsSkill4: 'Investigación de mercado.',
    metaAdsSkill5: 'Definición de estrategias efectivas.',
    metaAdsSkill6: 'Seguimiento, control y elaboración de informes de campaña.',
    googleAds: 'Google Ads',
    googleAdsSkill1: 'Más de 30 campañas realizadas para 15 empresas de distintos nichos.',
    googleAdsSkill2: 'Establecimiento de objetivos basados en auditorías, palabras clave, targets y buyers persona.',
    googleAdsSkill3: 'Investigación de mercado.',
    googleAdsSkill4: 'Determinación y combinación de estrategias.',
    googleAdsSkill5: 'Control de resultados y elaboración de informes de seguimiento.',
    experience1Title: 'Head of Product Design',
    experience1Period: 'Marzo 2024 – Abril 2025 ( 1 año y 1 mes )',
    experience1Location: 'Argentina · En remoto',
    experience1Description: 'Jornada completa. 100% remoto. Diseño y desarrollo web.',
    experience1Responsibilities: 'Brand Design and Identity System,UI Kit Design,Graphic Design,Application UX Design,Website UX Design,Website Developer,Website Optimization,Video Animations,Digital Marketing Strategy,Google Firebase/Analytics',
    experience2Title: 'CoFundador / CEO',
    experience2Period: 'Noviembre 2020 – Febrero 2024 ( 4 años 5 meses )',
    experience2Location: 'Argentina',
    experience2Description: 'Web Services. Development. UX/UI. Design System. Servicios web y marketing digital para clientes nacionales e internacionales (empresas, negocios, pymes y profesionales independientes).',
    experience2Responsibilities: 'Servicios activos con más de 50 clientes en proyectos web,Especialización en diseño UX/UI para sitios web,Gestión de desarrollo web, diseño web y mantenimiento,Manejo integral de proyectos desde el diseño hasta el lanzamiento,Liderazgo de un equipo de hasta 5 personas como WebMaster,Servicios de Marketing Digital y estrategia online,Gestión de dominios, Hosting SSD y correos profesionales,Soporte técnico y mantenimiento mensual de sitios web',
    experience3Title: 'Designer & Web Designer',
    experience3Period: 'Diciembre 2015 – Diciembre 2020 ( 4 años 11 meses )',
    experience3Location: 'Argentina',
    experience3Description: 'Gestión de más de 100 proyectos de clientes de forma independiente (freelance).',
    experience3Responsibilities: 'Desarrollo web y diseño UX/UI,Diseño gráfico y producción,Creación de sitios web responsivos,Optimización de sitios web,Gestión de proyectos web,Soporte técnico y mantenimiento',
    educationTitle: 'Educación',
    institution: 'Institución',
    education1Title: 'Técnico Superior en Diseño de Interfaces Digitales',
    education1Description: 'Actualmente en proceso las últimas materias de la carrera.',
    education2Title: 'Diseñador Gráfico',
    education2Description: 'Diseño gráfico, digital e impresión. Especialización en creación de logotipos, isotipos y branding, incluyendo la creación de manual de identidad corporativo.',
    education3Title: 'Diseñador Gráfico – UBA (FADU)',
    education3Description: 'Cursé la carrera durante 2 años antes de cambiar a ORT Argentina por su enfoque digital.',
    education4Title: 'Diseñador Web',
    education4Description: 'Especialización en diseño y desarrollo de sitios web, abarcando desde la maquetación hasta el diseño final, ofreciendo soluciones de calidad profesional.',
    education5Title: 'Ilustrador Digital – Puerta 18',
    education5Description: 'Espacio gratuito para jóvenes de 13 a 24 años, donde se fomentan habilidades y vocaciones a través del uso de herramientas tecnológicas.',
    experience1Title: 'Head of Product Design',
    experience1Period: 'Marzo 2024 – Abril 2025 (1 año 1 mes)',
    experience1Location: 'Argentina · En remoto',
    experience1Description: 'Jornada completa. 100% remoto. Diseño y desarrollo web.',
    experience1Responsibilities: 'Brand Design and Identity System,UI Kit Design,Graphic Design,Application UX Design,Website UX Design,Website Developer,Website Optimization,Video Animations,Digital Marketing Strategy,Google Firebase/Analytics',
    experience2Title: 'CoFundador / CEO',
    experience2Period: 'Noviembre 2020 – Febrero 2024 (4 años 5 meses)',
    experience2Location: 'Argentina',
    experience2Description: 'Web Services. Development. UX/UI. Design System. Servicios web y marketing digital para clientes nacionales e internacionales (empresas, negocios, pymes y profesionales independientes).',
    experience2Responsibilities: 'Servicios activos con más de 50 clientes en proyectos web,Especialización en diseño UX/UI para sitios web,Gestión de desarrollo web, diseño web y mantenimiento,Manejo integral de proyectos desde el diseño hasta el lanzamiento,Liderazgo de un equipo de hasta 5 personas como WebMaster,Servicios de Marketing Digital y estrategia online,Gestión de dominios, Hosting SSD y correos profesionales,Soporte técnico y mantenimiento mensual de sitios web',
    experience3Title: 'Designer & Web Designer',
    experience3Period: 'Diciembre 2015 – Diciembre 2020 (4 años 11 meses)',
    experience3Location: 'Argentina',
    experience3Description: 'Gestión de más de 100 proyectos de clientes de forma independiente (freelance).',
    experience3Responsibilities: 'Desarrollo web y diseño UX/UI,Diseño gráfico y producción,Creación de sitios web responsivos,Optimización de sitios web,Gestión de proyectos web,Soporte técnico y mantenimiento',
    experience4Title: 'Productor / Jefe de Depósito',
    experience4Company: 'BAM EVENT PLANNERS',
    experience4Period: 'Enero 2014 – Octubre 2015 (1 año 10 meses)',
    experience4Location: 'Argentina',
    experience4Description: 'Organización de eventos corporativos y sociales (coordinación, producción, logística y montajes).',
    experience4Responsibilities: 'Pre-organización y logística de ambientaciones y estructuras,Realización de presentaciones en PowerPoint para clientes,Asistencia en producción durante eventos,Coordinación con actores y artistas,Supervisión de seguridad en depósito y eventos,Logística de montajes y desmontajes,Realización de seguros RSA para eventos y promociones en vía pública',
    experience5Title: 'Asistente Administrativo Sénior',
    experience5Company: 'Shimano Latin America Representación Comercial Ltda.',
    experience5Period: 'Mayo 2013 – Octubre 2014 (1 año 6 meses)',
    experience5Location: 'Argentina',
    experience5Description: 'Asistencia administrativa integral en empresa multinacional del rubro de bicicletas y artículos deportivos.',
    experience5Responsibilities: 'Control de stock de muestras de mercadería,Gestión de pagos a proveedores, cobranzas y tareas bancarias,Elaboración de presupuestos y presentaciones,Manejo de caja chica para distintos departamentos,Control de gastos post eventos',
    contactDescription: '¿Tienes un proyecto en mente? Hablemos',
    linkedin: 'LinkedIn',
    email: 'Email',
    whatsapp: 'WhatsApp',
    whatsappMessage: 'Hola Tobias Etchelet, mi nombre es',
    languagesTitle: 'Idiomas',
    english: 'Inglés',
    englishLevel: 'C1 - Avanzado',
    englishDetails: 'First Certificate in English (FCE) – Bilingüe – Nativo',
    softwareTitle: 'Software',
    softwareLevelIntermediate: 'Nivel Intermedio',
    softwareLevelAdvanced: 'Nivel Avanzado',
    softwareLevelProfessional: 'Nivel Profesional',
    viewProject: 'Ver proyecto',
    uxuiTitle: 'Diseños UX/UI',
    uxuiProject1Title: 'Rediseño Bulgari',
    uxuiProject1Description: 'Rediseño de la experiencia de usuario y la interfaz para la tienda online de Bulgari, enfocándome en mejorar la navegación y la presentación de productos de lujo.',
    uxuiProject1Tech: 'Figma,UI Kit,User Research,Wireframing,Prototyping',
    uxuiProject2Title: 'Burger Bots App',
    uxuiProject2Description: 'Diseño de aplicación móvil para pedidos de hamburguesas con sistema de personalización de ingredientes y seguimiento en tiempo real del pedido.',
    uxuiProject2Tech: 'Adobe XD,User Flows,Interaction Design,Usability Testing',
    uxuiProject3Title: 'Proyectos en Codepen',
    uxuiProject3Description: 'Proyectos en html, css y javascript',
    uxuiProject3Tech:'html,css,javascript,a-frame-three.js,gsap',
  },
  en: {
    welcome: 'Welcome',
    enterVR: 'Enter VR',
    exitVR: 'Exit VR',
    generativeAI: 'Generative AI',
    videoAnimation: 'Video & Animation',
    textChatbots: 'Text Chatbots',
    designTools: 'Design Tools',
    socialMedia: 'Social Media',
    search: 'Search',
    audioTools: 'Audio Tools',
    codeTools: 'Code Tools',
    research: 'Research',
    otherTools: 'Other Tools',
    aiToolsTitle: 'AI Tools',
    aboutMe: 'About Me',
    graphicDesign: 'Graphic Design',
    webDesign: 'Web Design',
    uiUxDesign: 'UI/UX Design',
    webDevelopment: 'Web Development',
    uxUiDesign1: 'UI Design: Focused on the visual aspect, everything visible to the user.',
    uxUiDesign2: 'UX Design: Oriented to the user experience on the website or application.',
    aboutMeDescription: 'I have experience providing Web Design and Development solutions to real business problems, working with clients and teams at national and international levels, for clients in Argentina, United States, Uruguay and Spain. I specialized in Paid Media creating ads in Meta Ads and Google Ads. I use my skills in over 50 AI tools, applying them in my work development, improving quality, speed and automation of my work.',
    aboutMeMission: 'I love what I do! My mission is to help transform the lives of many people, businesses and companies, creating unique and high-quality web solutions and experiences.',
    projectsTitle: 'Projects',
    project1Title: 'Babz App',
    project1Description: 'Messaging platform with unique video reactions. Identity Design and Web Development. Complete product design including brand identity system, UI Kit and user experience.',
    project1Tech: 'UI Kit,Brand Design,UX Design,Firebase,Analytics',
    project2Title: 'SNS Web Services',
    project2Description: 'Comprehensive web services platform for over 50 clients, including SSD hosting, UX/UI design, web development and digital marketing.',
    project2Tech: 'UX/UI Design,Web Development,Hosting,Digital Marketing',
    project3Title: 'Neorelax',
    project3Description: 'Online store for relaxation and wellness products.',
    project3Tech: 'WordPress,WooCommerce,CSS,Payment Gateway',
    project4Title: 'Soluciones Gastronómicas',
    project4Description: 'E-commerce for gourmet food products.',
    project4Tech: 'WordPress,WooCommerce,JavaScript,UI/UX Design',
    project5Title: 'El Jardín de la Plaza',
    project5Description: 'Website design and development for kindergarden school.',
    project5Tech: 'WordPress,Elementor,CSS,Responsive Design',
    project6Title: 'Clazzical Interactive 3D Website',
    project6Description: 'Development of website with interactive 3D t-shirt.',
    project6Tech: 'Web Development,UX/UI Design,Web Design,React,Git',
    name: 'Tobias Etchelet',
    subtitle: 'Web Developer & UX/UI Designer',
    skillsTitle: 'Skills',
    experienceTitle: 'Experience',
    experienceLaboral: 'Professional Experience',
    contactTitle: 'Contact',
    webDeveloper: 'Web Developer',
    webDevSkills: 'HTML,CSS,JavaScript,Bootstrap 5',
    graphicDesign: 'Graphic Design',
    graphicDesignSkills: 'Design Theory,Color Theory,Typography,Graphic Production',
    webDesign: 'Web Design',
    webDesignSkills: 'Interface Design,Responsive Design,Content Management,WebMaster',
    uiUxDesign: 'UI/UX Design',
    uiUxDesign1: 'UI Design: Focused on the visual aspect, everything visible to the user.',
    uiUxDesign2: 'UX Design: Oriented to the user experience on the website or application.',
    metaAds: 'Meta Ads',
    metaAdsSkill1: 'More than 60 campaigns for 20 companies in different niches.',
    metaAdsSkill2: 'Internal and external audits.',
    metaAdsSkill3: 'Campaign objective setting.',
    metaAdsSkill4: 'Market research.',
    metaAdsSkill5: 'Definition of effective strategies.',
    metaAdsSkill6: 'Campaign monitoring, control and reporting.',
    googleAds: 'Google Ads',
    googleAdsSkill1: 'More than 30 campaigns for 15 companies in different niches.',
    googleAdsSkill2: 'Objective setting based on audits, keywords, targets and buyer personas.',
    googleAdsSkill3: 'Market research.',
    googleAdsSkill4: 'Determination and combination of strategies.',
    googleAdsSkill5: 'Results control and follow-up reporting.',
    languagesTitle: 'Languages',
    english: 'English',
    englishLevel: 'C1 - Advanced',
    englishDetails: 'First Certificate in English (FCE) - Bilingual - Native',
    softwareTitle: 'Software',
    softwareLevelIntermediate: 'Intermediate Level',
    softwareLevelAdvanced: 'Advanced Level',
    softwareLevelProfessional: 'Professional Level',
    skillsTitle: 'Skills',
    experienceTitle: 'Experience',
    experienceLaboral: 'Professional Experience',
    education: 'Education',
    contactTitle: 'Contact',
    webDeveloper: 'Web Developer',
    languagesTitle: 'Languages',
    english: 'English',
    englishLevel: 'C1 - Advanced',
    englishDetails: 'First Certificate in English (FCE) – Bilingual – Native',
    softwareTitle: 'Software',
    softwareLevelIntermediate: 'Intermediate Level',
    softwareLevelAdvanced: 'Advanced Level',
    softwareLevelProfessional: 'Professional Level',
    educationTitle: 'Education',
    institution: 'Institution',
    education1Title: 'Advanced Technician in Digital Interface Design',
    education1Description: 'Currently completing the final subjects of the program.',
    education2Title: 'Graphic Designer',
    education2Description: 'Graphic, digital and print design. Specialization in logo, isotype and branding creation, including corporate identity manual development.',
    education3Title: 'Graphic Designer - UBA (FADU)',
    education3Description: 'Studied the program for 2 years before switching to ORT Argentina due to its digital focus.',
    education4Title: 'Web Designer',
    education4Description: 'Specialization in website design and development, covering everything from wireframing to final design, offering professional quality solutions.',
    education5Title: 'Digital Illustrator - Puerta 18',
    education5Description: 'Free space for young people aged 13 to 24, fostering skills and vocations through the use of technological tools.',
    experience1Title: 'Head of Product Design',
    experience1Period: 'March 2024 – April 2025 (1 year 1 month)',
    experience1Location: 'Argentina · Remote',
    experience1Description: 'Full time. 100% remote. Web design and development.',
    experience1Responsibilities: 'Brand Design and Identity System,UI Kit Design,Graphic Design,Application UX Design,Website UX Design,Website Developer,Website Optimization,Video Animations,Digital Marketing Strategy,Google Firebase/Analytics',
    experience2Title: 'Co-Founder / CEO',
    experience2Period: 'November 2020 – February 2024 (4 years 5 months)',
    experience2Location: 'Argentina',
    experience2Description: 'Web Services. Development. UX/UI. Design System. Web and digital marketing services for national and international clients (businesses, companies, SMEs and independent professionals).',
    experience2Responsibilities: 'Active services with more than 50 clients in web projects,Specialization in UX/UI design for websites,Web development, web design and maintenance management,End-to-end project management from design to launch,Leadership of a team of up to 5 people as WebMaster,Digital Marketing and online strategy services,Domain management, SSD Hosting and professional emails,Technical support and monthly website maintenance',
    experience3Title: 'Designer & Web Designer',
    experience3Period: 'December 2015 – December 2020 (4 years 11 months)',
    experience3Location: 'Argentina',
    experience3Description: 'Management of more than 100 client projects independently (freelance).',
    experience3Responsibilities: 'Web development and UX/UI design,Graphic design and production,Responsive website creation,Website optimization,Web project management,Technical support and maintenance',
    experience4Title: 'Producer / Warehouse Manager',
    experience4Company: 'BAM EVENT PLANNERS',
    experience4Period: 'January 2014 – October 2015 (1 year 10 months)',
    experience4Location: 'Argentina',
    experience4Description: 'Organization of corporate and social events (coordination, production, logistics, and setups).',
    experience4Responsibilities: 'Pre-organization and logistics of settings and structures,Creating PowerPoint presentations for clients,Production assistance during events,Coordination with actors and artists,Security supervision in warehouse and events,Logistics of setups and dismantlings,Processing RSA insurance for events and promotions in public spaces',
    experience5Title: 'Senior Administrative Assistant',
    experience5Company: 'Shimano Latin America Commercial Representation Ltda.',
    experience5Period: 'May 2013 – October 2014 (1 year 6 months)',
    experience5Location: 'Argentina',
    experience5Description: 'Comprehensive administrative support in a multinational company in the bicycle and sports equipment industry.',
    experience5Responsibilities: 'Stock control of merchandise samples,Managing supplier payments, collections, and banking tasks,Preparing budgets and presentations,Handling petty cash for different departments,Post-event expense control',
    contactDescription: 'Do you have a project in mind? Let\'s talk',
    linkedin: 'LinkedIn',
    email: 'Email',
    whatsapp: 'WhatsApp',
    whatsappMessage: 'Hi Tobias Etchelet, my name is',
    viewProject: 'View project',
    uxuiTitle: 'UX/UI Designs',
    uxuiProject1Title: 'Bulgari Redesign',
    uxuiProject1Description: 'Redesign of the user experience and interface for Bulgari\'s online store, focusing on improving navigation and luxury product presentation.',
    uxuiProject1Tech: 'Figma,UI Kit,User Research,Wireframing,Prototyping',
    uxuiProject2Title: 'Burger Bots App',
    uxuiProject2Description: 'Mobile app design for burger orders with ingredient customization system and real-time order tracking.',
    uxuiProject2Tech: 'Adobe XD,User Flows,Interaction Design,Usability Testing',
    uxuiProject3Title: 'Codepen Web developments',
    uxuiProject3Description: 'Projects using html, css y javascript',
    uxuiProject3Tech:'html,css,javascript,a-frame-three.js,gsap',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es'); // Set default language to Spanish

  const getTranslation = (key) => {
    const currentTranslations = translations[language];
    return currentTranslations?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, getTranslation }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
