import React, { createContext, useContext, useState } from 'react';

// Definir las traducciones
const translations = {
  es: {
    web_designer: 'Diseñador Web & UX/UI',
    skills: 'Habilidades',
    software: 'Software',
    about_me: ' Sobre Mí',
    experience: ' Experiencia',
    education: ' Educación',
    ai_tools: ' Herramientas de IA',
    projects: 'Proyectos',
    ux_ui_designs: 'Diseños UX/UI',
    welcome: 'Bienvenido',
    aiTools: 'Herramientas de IA',
    contact: 'Contacto',
    enterVR: 'Entrar en VR',
    exitVR: 'Salir de VR',
    generativeAI: 'IA Generativa',
    videoAnimation: 'Video y Animación',
    textChatbots: 'Chatbots de Texto',
    designTools: 'Herramientas de Diseño',
    socialMedia: 'Redes Sociales',
    search: 'Búsqueda',
    audioTools: 'Herramientas de Audio',
    codeTools: 'Herramientas de Código',
    research: 'Investigación',
    otherTools: 'Otras Herramientas',
    aiToolsTitle: 'Herramientas de IA',
    aboutMe: 'Sobre Mí',
    graphicDesign: 'Diseño gráfico',
    webDesign: 'Diseño web',
    uiUxDesign: 'Diseño UX/UI',
    webDevelopment: 'Desarrollo web',
    aboutMeDescription: 'Tengo experiencia dando soluciones de Diseño y Desarrollo Web a problemas de negocios reales, tratando con clientes y equipos, a nivel nacional e internacional, para clientes de Argentina, Estados Unidos, Uruguay y España. Me especialicé en Paid Media creando anuncios en Meta Ads y Google Ads. Uso mis habilidades en más de 50 herramientas de Inteligencia Artificial (AI), y las aplico en el desarrollo de mi trabajo, mejorando la calidad, velocidad y automatización de mi trabajo.',
    aboutMeMission: 'Amo lo que hago! Mi misión es ayudar a transformar la vida de muchas personas, negocios y empresas, creando soluciones y experiencias web únicas y de alta calidad.',
    projectsTitle: 'Proyectos',
    project1Title: 'Babz App',
    project1Description: 'Plataforma de mensajería con reacciones de video únicas. Diseño de Identidad y Desarrollo Web. Diseño de producto completo incluyendo sistema de identidad de marca, UI Kit y experiencia de usuario.',
    project1Tech: 'UI Kit,Brand Design,UX Design,Firebase,Analytics',
    project2Title: 'SNS Web Services',
    project2Description: 'Plataforma integral de servicios web para más de 50 clientes, incluyendo hosting SSD, diseño UX/UI, desarrollo web y marketing digital.',
    project2Tech: 'UX/UI Design,Web Development,Hosting,Digital Marketing',
    project3Title: 'El Jardín de la Plaza',
    project3Description: 'Diseño y desarrollo de sitio web para escuela de jardín de infantes.',
    project3Tech: 'WordPress,Elementor,CSS,Responsive Design',
    project4Title: 'Soluciones Gastronómicas',
    project4Description: 'E-commerce para venta de productos gastronómicos.',
    project4Tech: 'WordPress,WooCommerce,JavaScript,UI/UX Design',
    project5Title: 'Neorelax',
    project5Description: 'Tienda online de productos de relajación y bienestar.',
    project5Tech: 'WordPress,WooCommerce,CSS,Payment Gateway',
    project6Title: 'Clazzical Interactive 3D Website',
    project6Description: 'Desarrollo de sitio web con remera 3D interactiva.',
    project6Tech: 'Web Development,UX/UI Design,Web Design,React,Git',
    name: 'Tobias Etchelet',
    subtitle: 'Desarrollador Web Full Stack y Diseñador UX/UI',
    skillsTitle: 'Habilidades',
    experienceTitle: 'Experiencia',
    experienceLaboral: 'Experiencia Laboral',
    educationTitle: 'Educación',
    contactTitle: 'Contacto',
    webDeveloper: 'Desarrollador Web',
    webDevSkills: 'HTML,CSS,JavaScript,Bootstrap 5',
    graphicDesignSkills: 'Teoría del Diseño,Teoría del Color,Tipografías,Producción Gráfica',
    webDesignSkills: 'Diseño de Interfaz,Diseño Responsivo,Gestión de Contenidos,WebMaster',
    uxUiDesign: 'Diseño UX/UI',
    uxUiDesign1: 'Diseño UI: Enfocado en la parte visual, todo lo visible para el usuario.',
    uxUiDesign2: 'Diseño UX: Orientado a la experiencia del usuario en la web o aplicación.',
    metaAds: 'Meta Ads',
    metaAdsSkill1: 'Más de 60 campañas realizadas para 20 empresas de diferentes nichos.',
    metaAdsSkill2: 'Auditoría interna y externa.',
    metaAdsSkill3: 'Establecimiento de objetivos para la campaña.',
    metaAdsSkill4: 'Investigación de mercado.',
    metaAdsSkill5: 'Definición de estrategias efectivas.',
    metaAdsSkill6: 'Seguimiento, control y elaboración de informes de campaña.',
    googleAds: 'Google Ads',
    googleAdsSkill1: 'Más de 30 campañas realizadas para 15 empresas de distintos nichos.',
    googleAdsSkill2: 'Establecimiento de objetivos basados en auditorías, palabras clave, targets y buyers persona.',
    googleAdsSkill3: 'Investigación de mercado.',
    googleAdsSkill4: 'Determinación y combinación de estrategias.',
    googleAdsSkill5: 'Control de resultados y elaboración de informes de seguimiento.',
    experience1Title: 'Head of Product Design',
    experience1Period: 'Marzo 2024 – Abril 2025 ( 1 año y 1 mes )',
    experience1Location: 'Argentina · En remoto',
    experience1Description: 'Jornada completa. 100% remoto. Diseño y desarrollo web.',
    experience1Responsibilities: 'Brand Design and Identity System,UI Kit Design,Graphic Design,Application UX Design,Website UX Design,Website Developer,Website Optimization,Video Animations,Digital Marketing Strategy,Google Firebase/Analytics',
    experience2Title: 'CoFundador / CEO',
    experience2Period: 'Noviembre 2020 – Febrero 2024 ( 4 años 5 meses )',
    experience2Location: 'Argentina',
    experience2Description: 'Web Services. Development. UX/UI. Design System. Servicios web y marketing digital para clientes nacionales e internacionales (empresas, negocios, pymes y profesionales independientes).',
    experience2Responsibilities: 'Servicios activos con más de 50 clientes en proyectos web,Especialización en diseño UX/UI para sitios web,Gestión de desarrollo web, diseño web y mantenimiento,Manejo integral de proyectos desde el diseño hasta el lanzamiento,Liderazgo de un equipo de hasta 5 personas como WebMaster,Servicios de Marketing Digital y estrategia online,Gestión de dominios, Hosting SSD y correos profesionales,Soporte técnico y mantenimiento mensual de sitios web',
    experience3Title: 'Designer & Web Designer',
    experience3Period: 'Diciembre 2015 – Diciembre 2020 ( 4 años 11 meses )',
    experience3Location: 'Argentina',
    experience3Description: 'Gestión de más de 100 proyectos de clientes de forma independiente (freelance).',
    experience3Responsibilities: 'Desarrollo web y diseño UX/UI,Diseño gráfico y producción,Creación de sitios web responsivos,Optimización de sitios web,Gestión de proyectos web,Soporte técnico y mantenimiento',
    educationTitle: 'Educación',
    institution: 'Institución',
    education1Title: 'Técnico Superior en Diseño de Interfaces Digitales',
    education1Description: 'Actualmente en proceso las últimas materias de la carrera.',
    education2Title: 'Diseñador Gráfico',
    education2Description: 'Diseño gráfico, digital e impresión. Especialización en creación de logotipos, isotipos y branding, incluyendo la creación de manual de identidad corporativo.',
    education3Title: 'Diseñador Gráfico – UBA (FADU)',
    education3Description: 'Cursé la carrera durante 2 años antes de cambiar a ORT Argentina por su enfoque digital.',
    education4Title: 'Diseñador Web',
    education4Description: 'Especialización en diseño y desarrollo de sitios web, abarcando desde la maquetación hasta el diseño final, ofreciendo soluciones de calidad profesional.',
    education5Title: 'Ilustrador Digital – Puerta 18',
    education5Description: 'Espacio gratuito para jóvenes de 13 a 24 años, donde se fomentan habilidades y vocaciones a través del uso de herramientas tecnológicas.',
    contactDescription: '¿Tienes un proyecto en mente? Hablemos',
    linkedin: 'LinkedIn',
    email: 'Email',
    whatsapp: 'WhatsApp',
    whatsappMessage: 'Hola Tobias Etchelet, mi nombre es',
    languagesTitle: 'Idiomas',
    english: 'Inglés',
    englishLevel: 'C1 - Avanzado',
    englishDetails: 'First Certificate in English (FCE) – Bilingüe – Nativo',
    softwareTitle: 'Software',
    softwareLevelIntermediate: 'Nivel Intermedio',
    softwareLevelAdvanced: 'Nivel Avanzado',
    softwareLevelProfessional: 'Nivel Profesional',
    viewProject: 'Ver proyecto',
    uxuiTitle: 'Diseños UX/UI',
  },
  en: {
    welcome: 'Welcome',
    enterVR: 'Enter VR',
    exitVR: 'Exit VR',
    generativeAI: 'Generative AI',
    videoAnimation: 'Video & Animation',
    textChatbots: 'Text Chatbots',
    designTools: 'Design Tools',
    socialMedia: 'Social Media',
    search: 'Search',
    audioTools: 'Audio Tools',
    codeTools: 'Code Tools',
    research: 'Research',
    otherTools: 'Other Tools',
    aiToolsTitle: 'AI Tools',
    aboutMe: 'About Me',
    graphicDesign: 'Graphic Design',
    webDesign: 'Web Design',
    uiUxDesign: 'UI/UX Design',
    webDevelopment: 'Web Development',
    aboutMeDescription: 'I have experience providing Web Design and Development solutions to real business problems, working with clients and teams at national and international levels, for clients in Argentina, United States, Uruguay and Spain. I specialized in Paid Media creating ads in Meta Ads and Google Ads. I use my skills in over 50 AI tools, applying them in my work development, improving quality, speed and automation of my work.',
    aboutMeMission: 'I love what I do! My mission is to help transform the lives of many people, businesses and companies, creating unique and high-quality web solutions and experiences.',
    projectsTitle: 'Projects',
    project1Title: 'Babz App',
    project1Description: 'Messaging platform with unique video reactions. Identity Design and Web Development. Complete product design including brand identity system, UI Kit and user experience.',
    project1Tech: 'UI Kit,Brand Design,UX Design,Firebase,Analytics',
    project2Title: 'SNS Web Services',
    project2Description: 'Comprehensive web services platform for over 50 clients, including SSD hosting, UX/UI design, web development and digital marketing.',
    project2Tech: 'UX/UI Design,Web Development,Hosting,Digital Marketing',
    project3Title: 'El Jardín de la Plaza',
    project3Description: 'Website design and development for kindergarten school.',
    project3Tech: 'WordPress,Elementor,CSS,Responsive Design',
    project4Title: 'Soluciones Gastronómicas',
    project4Description: 'E-commerce for gourmet food products.',
    project4Tech: 'WordPress,WooCommerce,JavaScript,UI/UX Design',
    project5Title: 'Neorelax',
    project5Description: 'Online store for relaxation and wellness products.',
    project5Tech: 'WordPress,WooCommerce,CSS,Payment Gateway',
    project6Title: 'Clazzical Interactive 3D Website',
    project6Description: 'Development of website with interactive 3D t-shirt.',
    project6Tech: 'Web Development,UX/UI Design,Web Design,React,Git',
    name: 'Tobias Etchelet',
    subtitle: 'Web Developer & UX/UI Designer',
    skillsTitle: 'Skills',
    experienceTitle: 'Experience',
    experienceLaboral: 'Professional Experience',
    education: 'Education',
    contactTitle: 'Contact',
    webDeveloper: 'Web Developer',
    languagesTitle: 'Languages',
    english: 'English',
    englishLevel: 'C1 - Advanced',
    englishDetails: 'First Certificate in English (FCE) – Bilingual – Native',
    softwareTitle: 'Software',
    softwareLevelIntermediate: 'Intermediate Level',
    softwareLevelAdvanced: 'Advanced Level',
    softwareLevelProfessional: 'Professional Level',
    educationTitle: 'Education',
    institution: 'Institution',
    education1Title: 'Advanced Technician in Digital Interface Design',
    education1Description: 'Currently completing the final subjects of the program.',
    education2Title: 'Graphic Designer',
    education2Description: 'Graphic, digital and print design. Specialization in logo, isotype and branding creation, including corporate identity manual development.',
    education3Title: 'Graphic Designer - UBA (FADU)',
    education3Description: 'Studied the program for 2 years before switching to ORT Argentina due to its digital focus.',
    education4Title: 'Web Designer',
    education4Description: 'Specialization in website design and development, covering everything from wireframing to final design, offering professional quality solutions.',
    education5Title: 'Digital Illustrator - Puerta 18',
    education5Description: 'Free space for young people aged 13 to 24, fostering skills and vocations through the use of technological tools.',
    contactDescription: 'Do you have a project in mind? Let\'s talk',
    linkedin: 'LinkedIn',
    email: 'Email',
    whatsapp: 'WhatsApp',
    whatsappMessage: 'Hi Tobias Etchelet, my name is',
    viewProject: 'View project',
    uxuiTitle: 'UX/UI Designs',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es'); // Set default language to Spanish

  const getTranslation = (key) => {
    const currentTranslations = translations[language];
    return currentTranslations?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, getTranslation }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
